# 生产环境配置
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/videosite?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1

videosite-app:
  include-path-patterns:
    - /comment/add
    - /videohub/edit
    - /videohub/add
    - /videohub/delete
    - /videohub/list
  admin-path-patterns:
    - /category/add
    - /videohub/audit
    - /user/list
  image-mime-patterns: image/*
  video-mime-patterns: video/*
  image-upload-folder: /upload/images
  video-upload-folder: /upload/videos
  jwt:
    issuer: SpringSecurity
    secret: hellovideosite1234hellovideosite
    expiration: 30
